***GCD***

In [54]:
def gcd(m,n):
    list1=[]
    list2=[]
    list3=[]
    for i in range(1,m+1):
        if m%i==0:
            list1.append(i)

    for j in range(1,n+1):
        if n%j==0:
            list2.append(j)

    for i in list1:
        if i in list2:
            list3.append(i)

    print(list3[-1])

In [55]:
gcd(14,63)

7


gcd(14,63)


In [10]:
def gcd(m,n):
    cf=[]
    for i in range(1,min(m,n)+1):
        if m%i==0 and n%i==0:
            cf.append(i)
    return (cf[-1])

In [11]:
gcd(14,63)

7

In [43]:
def gcd(m,n):
    
    for i in range(1,min(m,n)+1):
        if m%i==0 and n%i==0:
            mrcf=i
    return (mrcf)

In [44]:
gcd(14,63)

7

In [6]:
# using backward scan/loop

def gcd(m, n):
    for i in range(min(m, n), 0, -1):  
        if m % i == 0 and n % i == 0:
            return i  


In [7]:
gcd(14,63)

7

In [44]:
def gcd(m,n):
    i=min(m,n)
    while i>0:
        if m%i==0 and n%i==0:
            return i
        else:
            i=i-1

In [45]:
gcd(14,63)

7

**EUCLIDEAN**

In [7]:
def gcd(m,n):
    if n==0:
        return m
    else:
        while n!=0:
            m,n=n,m%n
        return m
            

In [8]:
gcd(12,33)

3

In [1]:
# RECCURSION

def gcd(m,n):
    if n==0:
        return m
    else:
        return gcd(n,m % n)
        return n

In [2]:
gcd(12,33)

3

In [21]:
def f(x):
   if x>0:
       f(x-1)
       f(x-2)
       print(x)

In [22]:
f(5)

1
2
1
3
1
2
4
1
2
1
3
5


In [7]:
n=int(input("enter the size="))
data=list(map(int,input("").split()))
x = data[::-1]
    
print(x)

enter the size= 5
 1 2 3 4 5


[5, 4, 3, 2, 1]


**ARRAY**

In [35]:
import array as arr

In [24]:
x=arr.array('i',[2,10,0,15,55])
type(x)
for i in x:
    print(i)

2
10
0
15
55


In [19]:
x.insert(3,20)
for i in x:
    print(i)

2
10
0
20
15
55


In [30]:
x.remove(20)
for i in x:
    print(i)

ValueError: array.remove(x): x not in array

In [26]:
x.index(0)
for i in x:
    print(i)

2
10
0
15
55


In [27]:
#update

x[1]=30  
for i in x:
    print(i)

2
30
0
15
55


In [9]:
import numpy as np

In [16]:
y=np.array([2,10,0,15,55])
type(y)
for i in y:
    print(i)

2
10
0
15
55


In [12]:
print(x[0])
print(x[4])

2
55


In [15]:
x.insert(3,20)
for i in x:
    print(i)

AttributeError: 'numpy.ndarray' object has no attribute 'insert'

In [1]:
n = int(input("Enter the size: "))
a = list(map(int, input("Enter the elements: ").split()))

x = a[::-1]
    
print(x)

Enter the size:  5
Enter the elements:  1 2 3 4 5


[5, 4, 3, 2, 1]


In [11]:
n = [1, 2, 3, 4, 5]
m = []

for i in range(len(n)):
    prod = 1
    for j in range(len(n)):
        if i != j:
            prod *= n[j]
            
    m.append(prod)

print(m)


[120, 60, 40, 30, 24]


In [6]:
n = [1, 2, 3, 4, 5]
m = []
t=[]

for i in range(len(n)):
    prod = 1
    l=1
    for j in range(len(n)):
        if i != j:
            prod *= n[j]//n[i]
            
    m.append(prod)



print(m)


[120, 0, 0, 0, 0]


In [46]:
def multiply_and_divide(numbers):

  product = 1
  for num in numbers:
    product *= num

  results = [product // num for num in numbers]
  return results

numbers = [1,2, 3, 4, 5]
output = multiply_and_divide(numbers)
print(output)

[120, 60, 40, 30, 24]


In [ ]:
# All numbers with specific difference

In [1]:



n=13
d=2
l=1
h=13

while l<=h:

    m=(l+h)//d
    s=sum(int(digit) for digit in str(m))
    if (m-s)<=d:
        l=m+1
    else:
        h=m-1

x=n-h
print(x)
        

4


In [13]:
#left rotation

def new(k):
    arr=[10,20,30,40]
    n=len(arr)
    if k>n:
        k=k-n
    elif k==0:
        print('no rotation')
    else:
        return arr[k:]+arr[:k] 


In [14]:
new(2)

[30, 40, 10, 20]

In [24]:
from array import*



In [25]:
array1=array('i',[10,20,30,40,50])
for x in array1:
    print(x)

10
20
30
40
50


In [26]:


print(array1[0])
print(array1[2])

10
30


In [27]:
array1.insert(1,60)
for x in array1:
    print(x)

10
60
20
30
40
50


In [28]:
array1.insert(5,60)
for x in array1:
    print(x)

10
60
20
30
40
60
50


In [29]:
array1.remove(40) #in deletion the index moves backward
for x in array1:
    print(x)

10
60
20
30
60
50


In [30]:
print(array1.index(50))  #searching

5


In [37]:
#update
from array import*

array2=('i',[10,20,30,40,50])
array2[20]=80
for x in array2:
    print(x)

TypeError: 'tuple' object does not support item assignment

In [35]:
from array import*

In [40]:
def new2(array3):
    array3=('i',[10,20,30,40])
    
    sum=0
    for x in array3:
        sum=sum+x

    l=len(array3)
    avg=sum//l
    return sum,avg

new(array3)
    
    

NameError: name 'array3' is not defined

In [39]:
import numpy as np
x=np.array([5,10,15,20])
def calc(x):
    l=len(x)
    add=np.sum(x)
    avg=add/l
    return add,avg

result=calc(x)
print(result)

(50, 12.5)


In [41]:
#reverse a array

import numpy as np
x=np.array([5,10,15,20])
print(x[::-1])


[20 15 10  5]


In [2]:
import numpy as np
x=np.array([5,10,15,20])
n=len(x)

for i in range(n-1,-1,-1):
    print(x[i])

20
15
10
5


In [7]:
#duplicates

#using looping and membership operator

import numpy as np
x=np.array([5,10,15,20,20,15])
new_arr=[]
for i in x:
    if i not in new_arr:
        new_arr.append(i)

print(new_arr)


[5, 10, 15, 20]


In [4]:
import numpy as np
x=np.array([5,10,15,20,20,15])
def dup(x):
    n_arr=[]
    for i in x:
        if i not in n_arr:
            n_arr.append(i)
    return n_arr

result=dup(x)
print(result)



[5, 10, 15, 20]


In [11]:
# using type conversion

import numpy as np
x=np.array([5,10,15,20,20,15])

def ndup(x):
    res=list(set(x))
    return np.array(res)

result=ndup(x)
type(result)
print(result)
    


[10 20  5 15]


In [17]:
# index of an element

array=('i',[10,20,30,40,50])
def new(n):
    try:
        
        for x in array:
            if x==n:
                return array.index(n)
    except ValueError:
        return -1
            

In [18]:
new(10)

In [23]:
from array import*

arr=('i',[10,20,30,40])
vrr=('i',[30,40,50,60])

x=set(arr[1])
y=set(vrr[1])

result=x&y
new=array('i',result)
print(new)

array('i', [40, 30])


In [1]:
from array import*

In [16]:
# last index of one

import numpy as np
x = np.array([0,0,1,1,0,1,0,1,0])
def last_1(x):
    index = -1
    
    for i in range(len(x)):
        if x[i] == 1:
            index =i
    return index
print("Last occurence 1:",last_1(x))

Last occurence 1: 7


In [36]:
#min and max value

import numpy as np
x=np.array([5,10,15,20])
def new(x):
    minv=np.min(x)
    maxv=np.max(x)
    return minv, maxv

result=new(x)
print(result)

(5, 20)


In [37]:
new(x)

(5, 20)

In [35]:
# setting 0 and 1 together


import numpy as np
x = np.array([0,0,1,1,0,1,0,1,0])
def last(x):
    count=0
    store=0
    for i in range(len(x)):
        if x[i]==0:
            count+=1
        else:
            if x[i]==1:
                store+=1
    return np.array([1]*store+[0]*count)
            


In [36]:
last(x)

array([1, 1, 1, 1, 0, 0, 0, 0, 0])

In [ ]:
# addition of matrix

In [ ]:
import numpy as np
x1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
x2 = np.array([[11,22,33],[44,55,66],[77,88,99]])
# result = x1+x2
# print(result)
def matrix_addition(x1,x2):
    result = []
    for i in range (len(x1)):
        row=[]
        for j in range(len(x1[0])):
            row.append(x1[i][j] + x2[i][j])
        result.append(row)
    return result
print(matrix_addition(x1,x2))

**RECURSION**

In [13]:
# using recursion

def factorial(n):
    fact=1
    if n==1:
        return fact
    else:
        return n*factorial(n-1)

In [15]:
factorial(5)

120

In [ ]:
#tower of hanoi

In [ ]:
# fibbonacci series

In [17]:
def fib(n):
    n=0
    n=1
    if n==0:
        return 0
    elif n==1:
        return 1
    else: 
        return f(n-1)+f(n-2)

In [18]:
fib(6)

1

In [ ]:
# TOWER OF HANOI

In [26]:
def tower(n,a,b,c):
    
    if n==1:
        print("move first disc from",a, "to", c)
        
        return
    elif n==0:
        return 'error'
    else:
        tower(n-1,a,c,b)
        print("move",n,"th disk from",a,"to",c)
        tower(n-1,b,a,c)
    

     
        

In [27]:
tower(4,'a','b','c')

move first disc from a to b
move 2 th disk from a to c
move first disc from b to c
move 3 th disk from a to b
move first disc from c to a
move 2 th disk from c to b
move first disc from a to b
move 4 th disk from a to c
move first disc from b to c
move 2 th disk from b to a
move first disc from c to a
move 3 th disk from b to c
move first disc from a to b
move 2 th disk from a to c
move first disc from b to c


**LINKED LIST**

In [ ]:
# OOPs concept

In [5]:
class Person:
    def __init__(self,name,age):
        self.name=name
        self.age=age
    def dispaly(self):
        print(f"Name:{self.name}")
        print(f"Age:{self.age}")

hello=Person("manish",22)
hello.dispaly()
        



Name:manish
Age:22


In [6]:
class Supermarket:
    def purchase(unique):
        print("toys")
        print("gifts")

customer=Supermarket()
customer.purchase()

toys
gifts


In [ ]:
class Node:
    def __init__(self,data,pointer):
        self.data=data
        self.pointer=pointer
class LinkedList:
    def append(self,data):

    def display(self):
        

In [ ]:
# creating a linked list

In [ ]:
# REVERSING LINKED LIST

In [1]:
class Node:
    def __init__(self, data):
        self.data = data
        self.next = None

class LinkedList:
    def __init__(self):
        self.head = None

    def append(self, data):
        new_node = Node(data)
        if not self.head:
            self.head = new_node
            return
        temp = self.head
        while temp.next:
            temp = temp.next
        temp.next = new_node

    def print_list(self):
        temp = self.head
        while temp:
            print(temp.data, end=" -> ")
            temp = temp.next
        print("None")

    def reverse(self):
        prev = None
        current = self.head
        while current:
            next_node = current.next  
            current.next = prev       
            prev = current           
            current = next_node      
        self.head = prev


ll = LinkedList()
ll.append(1)
ll.append(2)
ll.append(3)
ll.append(4)

print("Original Linked List:")
ll.print_list()

ll.reverse()
print("Reversed Linked List:")
ll.print_list()


Original Linked List:
1 -> 2 -> 3 -> 4 -> None
Reversed Linked List:
4 -> 3 -> 2 -> 1 -> None


In [ ]:
# Insertion at the begining in a linked list 

In [ ]:
class node:
    def__init__(self, Newdata=None,link=None):
    

In [ ]:
# Insertion at the end in a linked list 

In [3]:
class node:
    def __init__(self, newData=None, link=None):
        self.data=newData
        self.next=link

class singlelinkedlist:
    def __init__(self):
        self.Head=None
    def insert_end(self, newData):
        newNode=Node(newData)
        if self.Head is None:
            self.Head=newNode
        else:
            curNode=self.Head
            while curnode.next is not None:
                curNode=curNode.next
            curNode.next=newNode

          # function to insert a node at the beginning of the list

    def insert_begin(self, newData):
         self.Head=Node(newData, self.head)

    def insert_before_nth(self.newData, location):
         if self.head is None or location ==1:
             self.Head=Node(newData, self.Head)
         else:
             curNode=self.Head
             c=1
             while c < location - 1 and curNode.next is not None:
                 c+=1
                 curNode=curNode.next
            newNode=Node(newData, curNode.next)
            curNode.next=newNode
    def insert_after_nth(self, newData, location):
        if self.Head is None:
            self.Head=Node(newData,self.Head)
        else:
            curNode=self.Head
            c=1
            while c<1 location and curNode.next is not None:
                c+=1
                curNode.next=Node(newData, curNode.next)

     def delete_first(self):
         if self.Head is None:
             print("empty list. deletion not possible")
         else:
             curNode = self.Head
             self.Head=self.Head.next
             del(curNode)
             print("node deleted successfully")

     def delete_last(self):
         if self.Head is None:
             print("empty list. deletion not possible")
         elif self.Head.next is None:
             del(self.Head)
             self.Head=None
         else:
             curNode=self.Head
             while curNode.next.next is not None:
                 curNode=curNode.next
             del(curNode.next)
             curNode.next=None
             print("node deleted successfully")

     def delete_anynode(self,num):
         if self.Head is None:
             print("empty list.deletion not possible")
         else:
             curNode=self.Head
             if curNode.Data==num:
                 self.head=self.Head.Next
                 del(curNode)
                 print("Node deleted successfully")
             else:
                 flag=0
                 prev=None
                 while curNode is not None:
                     if curNode.Data
                




IndentationError: unindent does not match any outer indentation level (<string>, line 33)